[package]
name = "composable-tasks-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = ["you"]

[dev-dependencies]

[dependencies.composable-tasks]
path = ".."

[dependencies.multiversx-sc-meta]
version = "=0.53.2"
default-features = false
