[package]
name = "farm-extra-rewards-wrapper"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.farm]
git = "https://github.com/multiversx/mx-exchange-sc"
rev = "fdb1fb4"

[dev-dependencies]
num-bigint = "0.4.2"

[dependencies.multiversx-sc]
version = "=0.39.4"

[dev-dependencies.multiversx-sc-scenario]
version = "=0.39.4"
