[package]
name = "auto-farm-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = ["you"]

[dev-dependencies]

[dependencies.auto-farm]
path = ".."

[dependencies.multiversx-sc-meta]
version = "=0.50.0"
default-features = false
